services:
  db:
    image: postgres:17.5
    container_name: documentai-db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: documentai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  db: