spring:
  application:
    name: documentai
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/documentai
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: false
  messages:
    basename: lang/messages
server:
  port: 9090